config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html

  resources :artists, except: :edit
  get '/artists/:id/edit', to: 'artists#edit', as: 'edit_artist'
  resources :genres
  # , except: :edit
  # get '/genres/:id/edit', to: 'genres#edit', as: 'edit_genre'

  resources :songs
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/artist.rb
class Artist < ApplicationRecord
    has_many :songs
    has_many :genres, through: :songs
end

app/models/genre.rb
class Genre < ApplicationRecord
    has_many :songs
    has_many :artists, through: :songs
end

app/models/song.rb
class Song < ApplicationRecord
    belongs_to :artist
    belongs_to :genre
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/artists_controller.rb
class ArtistsController < ApplicationController
    def index
        @artists = Artist.all
    end

    def new
        @artist = Artist.new
    end

    def show
        @artist = Artist.find(params[:id])
    end

    def create
        @artist = Artist.new(artist_params)
        @artist.save
        redirect_to @artist
    end

    def update
        @artist = Artist.find(params[:id])
        @artist.update(artist_params)
        redirect_to @artist
    end

    def edit
        @artist = Artist.find(params[:id])
    end

    def destroy
        @artist = Artist.find(params[:id])
        @artist.destroy
        redirect_to @artist
    end

    # private
    def artist_params
        params.require(:artist).permit(:name)
    end
end

app/controllers/genres_controller.rb
class GenresController < ApplicationController

    def index
        @genres = Genre.all        
    end

    def show
        @genre = Genre.find(params[:id])
    end

    def new
        @genre = Genre.new
    end

    def edit
        @genre = Genre.find(params[:id])
    end
    
    def create
        @genre = Genre.new(genre_params)
        @genre.save
        redirect_to genre_path(@genre.id)
    end

    def update
        @genre = Genre.find(params[:id])
        @genre.update(genre_params)
        redirect_to genre_path(@genre.id)
    end

    def destroy
        @genre = Genre.find(params[:id]) 
        @genre.destroy
        redirect_to genres_path
    end

    private

    def genre_params
        params.require(:genre).permit(:title)
    end
    
end

app/controllers/songs_controller.rb
class SongsController < ApplicationController

    def index
        @songs = Song.all
    end

    def show
        @song = Song.find(params[:id])
    end

    def new
        @song = Song.new
    end

    def edit
        @song = Song.find(params[:id])
    end

    def create
        a = Artist.find_by_name(params[:song][:artist])
        g = Genre.find_by_name(params[:song][:genre])

        s = Song.new
        s.title = params[:song][:title]
        s.artist = a
        s.genre = g
        s.save
        
        redirect_to song_path(s.id)
    end
   
    def update
        s = Song.find(params[:id])
        # s.title = song_params[:title]

        # artist_id = song_params[:artist_id]
        # artist = Artist.find_by(name: artist_name)
        # s.artist = artist
   
        # genre_id = song_params[:genre_id]
        # genre = Genre.find_by(title: genre_title)
        # s.genre = genre
    
        s.update(song_params)
        # s.save
    
        redirect_to song_path(s.id)
       
    end

    def destroy
        @song = Song.find(params[:id])
        @song.destroy
        redirect_to songs_path
    end

    private 
    def song_params
        params.require(:song).permit(:title, :artist_id, :genre_id)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/artists_helper.rb
module ArtistsHelper
end

app/helpers/genres_helper.rb
module GenresHelper
end

app/helpers/songs_helper.rb
module SongsHelper
end

app/views/artists/_form.html.erb
<h3> Artist Form</h3>

<%= form_for(@artist) do |f| %>
<%= f.label :name%><br>
<%= f.text_field :name %><br>
<%= f.submit%>
<% end %>

app/views/artists/edit.html.erb
<h1>Edit Artist</h1>
<%= render "form", artist: @artist%>

app/views/artists/index.html.erb
<% @artists.each do |artist| %>

<%= link_to  "#{artist.name}", artist_path(artist.id) %><br>

<% end %>

app/views/artists/new.html.erb
<h1>New Artist</h1>
<%= render "form", artist: @artist%>

app/views/artists/show.html.erb
<h1><%= @artist.name%> </h1>
<h4>This Artist has this Songs:</h4>
<nav><% @artist.songs.each do |song|%></nav>
<h5><strong><%= link_to  "#{song.title}", song_path(song.id) %></strong></h5>
<%end%>
<%= link_to  "Back", artists_path %><br>
<%= link_to  "Edit Artist?", edit_artist_path %><br>
<%= link_to("Delete Artist?", artist_path(@artist.id), method: :delete, data: {confirm: "R u sure u Wanna delete this artist?"}) %><br>

app/views/genres/_form.html.erb
<h1> Form </h1>
<%= form_for (@genre) do |f| %>
   <%= f.label :title%>
   <%= f.text_field :title%>

   <%= f.submit%>
<% end %>

app/views/genres/edit.html.erb
<h1>Edit Genre </h1>
<h2><%= render "form", genre: @genre%> </h2>

app/views/genres/index.html.erb
<%@genres.each do |genre|%>
    <%= link_to "#{genre.title}", genre_path(genre.id) %><br>
<%end%>

app/views/genres/new.html.erb
<h1>New Genre</h1>
<h2><%= render "form", genre: @genre%> </h2>

app/views/genres/show.html.erb
<h1>Genre Page</h1>
<%=@genre.title%><br>

<p>This Genre has these songs:</p>
<nav><%@genre.songs.each do |song|%></nav>
<%= link_to "#{song.title}" , song_path(song.id) %><br>

<%end%>
<%= link_to  "Back", genres_path %><br>
<%= link_to  "Edit Genre?", edit_genre_path(@genre.id) %><br>
<%= link_to("Delete Genre?", genre_path(@genre.id), method: :delete, data: {confirm: "R u sure u Wanna delete this genre?"}) %><br>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Music</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
  <h3><%= link_to  "All Artists", artists_path %><br></h3>
  <h3><%= link_to  "All Songs", songs_path %><br></h3>
  <h3><%= link_to  "All Genres", genres_path %><br></h3>

    <%= yield %>
  </body>
</html>

app/views/songs/_form.html.erb
<h3> Song Form</h3>

<%= form_for(@song) do |f| %>
<%= f.label :title%><br>
<%= f.text_field :title %><br>

<% artist_names = Artist.all.map{|a| a.name} %>
<% genre_title = Genre.all.map{|a| a.title} %>

<%= f.label :artist%><br>
<%= f.collection_select :artist_id, Artist.all, :id, :name%>

<%= f.label :genre%><br>
<%= f.collection_select :genre_id, Genre.all, :id, :title%>

<%= f.submit%>
<% end %>

app/views/songs/edit.html.erb
<h1>Edit Song</h1>
<%= render "form", song: @song%>

app/views/songs/index.html.erb
<% @songs.each do |song| %>

<%= link_to  "#{song.title}", song_path(song.id) %><br>

<% end %>

app/views/songs/new.html.erb
<h1>New Song</h1>
<%= render "form", song: @song%>

app/views/songs/show.html.erb
<h1><%= @song.title%> </h1>
<h2>By: <%= link_to  "#{@song.artist.name}", artist_path(@song.artist.id) %> </h2>
<h2>In this genre: <%= link_to  "#{@song.genre.title}", artist_path(@song.genre.id) %> </h2>

<%= link_to  "Back", songs_path %><br>
<%= link_to  "Edit song?", edit_song_path %><br>
<%= link_to("Delete song?", song_path(@song.id), method: :delete, data: {confirm: "R u sure u Wanna delete this song?"}) %><br>